# Generated by Django 5.2.11 on 2026-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwork',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
